apiVersion: v1
kind: ConfigMap
metadata:
  name: gwc-exporter-config
  namespace: monitoring
  labels:
    app: gwc-exporter
data:
  GWC_TARGET_URL: "http://geowebcache:8080/geowebcache"
  GWC_WEB_LISTEN_ADDRESS: ":9109"
  GWC_WEB_TELEMETRY_PATH: "/metrics"
  GWC_SCRAPE_TIMEOUT: "5s"
