apiVersion: v1
kind: Service
metadata:
  name: gwc-exporter
  namespace: monitoring
  labels:
    app: gwc-exporter
spec:
  type: ClusterIP
  selector:
    app: gwc-exporter
  ports:
    - name: metrics
      port: 9109
      targetPort: metrics
      protocol: TCP
